language: cpp
compiler:
  - gcc
  - clang

install:
  - sudo apt-get update
#Use clang 3.5 for compilation
  - sudo apt-add-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" -y
  - sudo apt-add-repository "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main" -y
  - sudo apt-get update
  - sudo apt-get install clang-3.5 -y --force-yes
  - export LD_LIBRARY_PATH=/usr/lib/llvm-3.5/lib/
  - export PATH=/usr/lib/llvm-3.5/bin:$PATH
  - clang --version
#Download and compile dependencies
  - sudo apt-get install p7zip-full
    #SFML dependencies:
  - sudo apt-get install libopenal-dev libjpeg-dev libglew-dev libudev-dev libxrandr-dev libsndfile1-dev libglu1-mesa-dev libfreetype6-dev
#Compile the tests only
  - mkdir .build-tests
  - cd .build-tests
  - cmake -DBUILD_GDJS=FALSE -DBUILD_IDE=FALSE -DBUILD_EXTENSIONS=FALSE -DBUILD_TESTS=TRUE -DNO_GUI=TRUE ..
  - make -j 4
  - cd ..
#Install GDJS tests dependencies
  - cd GDJS/tests
  - npm install
  - cd ../..

script:
#GDJS game engine tests:
  - cd GDJS/tests
  - npm test
  - cd ../..
#GDCore and GDCpp game engine tests:
  - cd .build-tests
# - export LD_LIBRARY_PATH=$PWD/Binaries/Output/Release_Linux:$PWD/.build-tests/ExtLibs/SFML/lib:$LD_LIBRARY_PATH
  - Core/GDCore_tests
  - GDCpp/GDCpp_tests